#!/usr/bin/env perl

use strict;
use warnings;
use Cwd;

my $dir = getcwd();

my $distros = {
    'debian' => [
      '7',
      '8',
      '9',
    ],
    'ubuntu' => [
      '12.04',
      '14.04',
      '16.04',
    ],
    'centos' => [
      '7',
    ],
    'fedora' => [
      '25',
      '26',
    ],
    'alpine' => [
      '3.5',
      '3.6',
    ],
    'opensuse' => [
      '42.3',
    ],
    'base/archlinux' => [
      'latest',
    ],
};

sub run {
  my @args = @_;
  print(join(' ',@args)."\n");
  system(@args);
  if($? & 127) {
    print(join(' ',@args)."\n");
    printf("Termsig: %d\n",$? & 127);
    exit(1);
  }
  else {
    my $exitcode = $? >> 8;
    if($exitcode != 0) {
      print(join(' ',@args)."\n");
      printf("Exitcode: %d\n",$exitcode);
      exit(1);
    }
  }
}

my @distros_to_test;

if(defined($ARGV[0])) {
    if($ARGV[0] =~ m/:/) {
        run('docker', 'pull', $ARGV[0]);
        run('docker', 'run', '--rm', '-ti', '-v', "${dir}:/tmp/multistreamer-installer", $ARGV[0], "/tmp/multistreamer-installer/install");
        exit(0);
    }

    push(@distros_to_test,$ARGV[0]);
}
else {
    @distros_to_test = keys %$distros;
}


foreach my $distro (@distros_to_test) {
    foreach my $version (@{$distros->{$distro}}) {
        print "Testing ${distro}:${version}\n";
        run('docker', 'pull', "${distro}:${version}");
        run('docker', 'run', '--rm', '-ti', '-v', "${dir}:/tmp/multistreamer-installer", "${distro}:${version}", "/tmp/multistreamer-installer/install");
    }
}

